# Generated by Django 4.2.16 on 2024-11-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos_ar_condicionado', '0002_camada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camada',
            name='ambiente',
        ),
        migrations.AddField(
            model_name='ambiente',
            name='camadas',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='camada',
            name='espessura',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
