# Generated by Django 4.2.16 on 2024-11-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculos_ar_condicionado', '0004_camada_condutividade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camada',
        ),
    ]
