# Generated by Django 4.2.16 on 2024-11-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculos_ar_condicionado', '0006_rename_camadas_ambiente_camadas_json_camada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='camadas_json',
        ),
    ]
