# Generated by Django 4.2.16 on 2024-11-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos_ar_condicionado', '0007_remove_ambiente_camadas_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='temperatura_externa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='temperatura_interna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
