# Generated by Django 4.2.16 on 2024-11-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos_ar_condicionado', '0009_alter_ambiente_temperatura_externa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='quantidade_de_eletronicos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='quantidade_de_lampadas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='quantidade_de_pessoas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
